version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./config.json:/app/config.json
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - MODEL_NAME=${MODEL_NAME}
      - TRANSLATE_MODEL=${TRANSLATE_MODEL}
      - LOG_LEVEL=${LOG_LEVEL}
    env_file:
      - .env
    networks:
      - btmr-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:${BACKEND_PORT:-8000}
    depends_on:
      - backend
    networks:
      - btmr-network

networks:
  btmr-network:
    driver: bridge